services:
  back-end:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "5252:5252"  # Map the port of the container to the host
    networks:
      - app-network  # Use a custom network

  front-end:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "80:80"  # Map the port of the container to the host
    networks:
      - app-network  # Use a custom network

  proxy:
    build:
      context: ./proxy  # Ensure this points to the proxy directory
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Expose proxy on port 8080
    networks:
      - app-network  # Use the same custom network
    depends_on:
      - front-end
      - back-end

networks:
  app-network:  # Define a custom network
    driver: bridge
