version: '3'
services:
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  back-end-1:
    image: your_api_image
    ports:
      - "5251:5251"
    networks:
      - app-network

  back-end-2:
    image: your_api_image
    ports:
      - "5252:5252"
    networks:
      - app-network

  front-end:
    image: your_frontend_image
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
