version: '3.8'

services:
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  back-end-1:
    build:
      context: ./back-end  # Path to the Dockerfile for back-end-1
    ports:
      - "5251:5251"
    networks:
      - app-network

  back-end-2:
    build:
      context: ./back-end  # Path to the Dockerfile for back-end-2
    ports:
      - "5252:5252"
    networks:
      - app-network

  front-end:
    build:
      context: ./front-end  # Path to the Dockerfile for the front-end
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
